"""
A module for ML-based Quantum Error Mitigation (MLQEM) methods.

Contents:
- MLQEM: An abstract base class for ML-based Quantum Error Mitigation methods.
- QEMRandomForest: A concrete implementation of MLQEM using Random Forest Regressors for Hadamard test circuits.
- generate_data: A function to generate training data by simulating parameterized quantum circuits with and without noise.

@author pconstant
"""

import pickle
from tqdm import tqdm
from dataclasses import dataclass
from abc import ABC, abstractmethod

import numpy as np
from matplotlib import pyplot as plt

from sklearn.ensemble import RandomForestClassifier, GradientBoostingRegressor, RandomForestRegressor
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, TensorDataset
from torch import Tensor

from qiskit.quantum_info import Statevector, SparsePauliOp
from qiskit_aer import AerSimulator

from qiskit_helpers.simulate_circuit import simulate_circ

# raise NotImplementedError("This module is still in development and not ready for use.")

@dataclass
class RFParams:
    pass

class MLQEM(ABC):
    """
    A parent class for all ML-based Quantum Error Mitigation methods.
    """

    @abstractmethod
    def run(self, angles, noisy_exp_vals):
        """
        Predict the measured quantity based on the prediction of the ML model.
        
        :param angles: the parameterized circuit angles
        :param noisy_exp_vals: the noisy expectation value to be imporved
        :return: the mitigated expectation value
        """
        pass

    @abstractmethod
    def load_model(self, model_file):
        """
        Load an already trained model. The model is stored via `fit()`.
        
        :param model_file: The file that contains the model.
        """
        pass

    @abstractmethod
    def evaluate(self):
        """
        Evaluate the models performance, based on an architecture-native metric.
        """        
        pass

    @abstractmethod
    def fit(self, data_file, model_file="qem_model.pkl", test_size=0.2, seed=42, **options):
        """
        Docstring for fit
        
        :param data_file: The csv file containing the dataset.
        :param model_file: The file to which the trained model will be stored.
        :param test_size: The percentage of the data to be used for testing (can be zero).
        :param seed: The seed to initialize random processes.
        :param options: Model-native parameters.
        """
        pass
    
    @abstractmethod
    def run(self, angles, noisy_exp_vals):
        pass

    def load_data(self, file_path):
        """
        Loads data from a CSV file generated by `generate_data` function.
        
        :param file_path: Path to the CSV file
        :param num_qubits: Number of qubits in the circuit
        :return: tuple of (angles, ideal_exp_vals, noisy_exp_vals)
        """
        data = np.loadtxt(file_path, delimiter=',')
        n_params = data.shape[1] - 2  # subtract 2 for ideal and noisy exp vals
        
        angles = data[:, :n_params]
        ideal_exp_vals = data[:, -2]
        noisy_exp_vals = data[:, -1]
        
        return angles, ideal_exp_vals, noisy_exp_vals




class QEMRandomForest(MLQEM):
    """
    Implements Quantum Error Mitigation using Random Forest Regressor models for Hadamard test circuits.
    """

    def __init__(self, model_file=None):
        """
        Initialize the QEMRandomForest class. If a model_file is provided, load the trained model.

        :param model_file: The filename to load the trained model from
        """
        if model_file is not None:
            self.load_model(model_file)
            print(f"Loaded model from {model_file}")


    def load_data(self, file_path):
        """
        Loads data from a CSV file generated by `generate_data` function.
        
        :param file_path: Path to the CSV file
        :param num_qubits: Number of qubits in the circuit
        :return: tuple of (angles, ideal_exp_vals, noisy_exp_vals)
        """
        data = np.loadtxt(file_path, delimiter=',')
        n_params = data.shape[1] - 2  # subtract 2 for ideal and noisy exp vals
        
        angles = data[:, :n_params]
        ideal_exp_vals = data[:, -2]
        noisy_exp_vals = data[:, -1]
        
        return angles, ideal_exp_vals, noisy_exp_vals
        

    def fit(self, data_file, n_estimators=200, model_file="rfr_qem_model.pkl", test_size=0.2, seed=42):
        """
        Fit Random Forest Regressor models to the data.
        
        :param data_file: The CSV file containing training data
        :param n_estimators: Number of trees in the forest
        :param model_file: The filename to save the trained models
        :param seed: The random seed for reproducibility
        """
        
        self.angles, self.ideal_exp_vals, self.noisy_exp_vals = self.load_data(data_file)
        
        X = np.concatenate([self.angles, self.noisy_exp_vals.reshape(-1, 1)], axis=1)
        y = self.ideal_exp_vals
        
        if test_size is None:
            self.X_train = X
            self.X_test = None
            self.y_train = y
            self.y_test = None
        else:
            self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(
                X, y, 
                test_size=test_size, 
                random_state=seed
            )

        rfr = RandomForestRegressor(n_estimators=n_estimators, random_state=seed)
        rfr.fit(self.X_train, self.y_train)

        self.rfr = rfr

        with open(model_file, "wb") as f:
            pickle.dump(rfr, f)
        
    def load_model(self, model_file):
        """
        Load a trained Random Forest Regressor model from file.
        
        :param model_file: The filename to load the trained model from
        """
        with open(model_file, "rb") as f:
            self.rfr = pickle.load(f)

    def evaluate(self):
        """
        Evaluate the trained model on test data. If perfect, R^2 score should be close to 1.
        
        :return: The R^2 score of the model
        """
        if not hasattr(self, 'rfr'):
            raise ValueError("Model not trained. Please call fit() before evaluate().")
        if self.X_test is None or self.y_test is None:
            raise ValueError("No test data available for evaluation.")
        
        score = self.rfr.score(self.X_test, self.y_test)
        return score

    def run(self, angles, noisy_exp_vals):
        """
        Estimate the ideal expectation values from noisy data using the trained model.
        
        :param angles: Rotation angles (2D array with shape [n_samples, n_params])
        :param noisy_exp_vals: Noisy expectation values (1D array with shape [n_samples])
        :return: The estimated ideal expectation values
        """
        if not hasattr(self, 'rfr'):
            raise ValueError("Model not trained. Please call fit() before run().")
        
        # Combine features in same format as training data
        X = np.concatenate([angles, noisy_exp_vals.reshape(-1, 1)], axis=1)
        return self.rfr.predict(X)



def set_model():
    """
    Loads and sets the give ML model before the algorithm run.
    """


def generate_data(circuit, nm_params, file_path, items=10000, seed=42):
    """
    Generates data by simulating the given circuit both with and without noise.
    
    :param circuit: The relevant parameterized quantum circuit.
    :param nm_params: The noise model parameters to apply during noisy simulation.
    :param file_path: The path to save the generated data.
    """
    np.random.seed(seed)
    n_params = circuit.num_parameters
    to_save = np.zeros((items, n_params + 2)) # we could add the noise parameters here as well

    all_z = SparsePauliOp('I' * (circuit.num_qubits - 1) + 'Z')
    for i in tqdm(range(items), leave=True):
        anlges = np.random.uniform(-np.pi, np.pi, n_params)
        
        sv = simulate_circ(circuit, anlges, type="statevector", noise_model_params=None)
        dm = simulate_circ(circuit, anlges, type="statevector", noise_model_params=nm_params)
        ideal_exp_val = sv.expectation_value(all_z).real
        noisy_exp_val = dm.expectation_value(all_z).real
        
        to_save[i, :] = np.concatenate([anlges, [ideal_exp_val], [noisy_exp_val]])

    np.savetxt(file_path, to_save, delimiter=',')



if __name__ == "__main__":
    from qiskit.circuit.library import n_local
    from qiskit_helpers import DepolarizingErrorParams
    from qnpu_circuits import overlap_circ

    ansatz = n_local(4, rotation_blocks=['ry', 'rz'], entanglement_blocks='cx', reps=1)
    nm = DepolarizingErrorParams(single_qubit_error_rate=0.01, two_qubits_error_rate=0.03)

    generate_data(ansatz, nm, "test.csv", items=1000)

    qem = QEMRandomForest("test.csv", test_size=0.2, seed=2026)
    qem.fit(fname="rfr_model.pkl")
    score = qem.evaluate()
    print(f"R^2 score: {score}")

    

    